commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentUpdateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path("create/", CommentCreateView.as_view(), name="create"),
    path("update/<int:pk>/", CommentUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete"),
]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('article/', include('articleapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('like/', include('likeapp.urls')),

    path('', hello_world)
] + static(
    settings.MEDIA_URL, document_root = settings.MEDIA_ROOT,
)

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

from articleapp.models import Article


# Create your models here.
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=False,
                                related_name='comments')
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=False,
                               related_name='comments')
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]

commentapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView

from commentapp.decorators import comment_ownership_required
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment


# Create your views here.
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = "commentapp/create.html"

    def form_valid(self, form):
        form.instance.writer = self.request.user
        form.instance.article_id = self.request.POST.get('article_pk')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.article.pk})

@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentCreationForm
    context_object_name = 'target_comment'
    template_name = 'commentapp/update.html'
    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.article.pk})

@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.article.pk})

commentapp/templates/commentapp/create.html
{% load bootstrap4 %}

    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'commentapp:create' %}"
              method="post"
              enctype="multipart/form-data">

            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="hidden"
                    name="article_pk"
                    value="{{  target_article.pk }}">
            
            <div class="text-end">
                <button class="btn btn-warning rounded-pill px-5 my-2" type="submit">
                Submit
                </button>
            </div>

        </form>

    </div>

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class = "my-5">
        <h1>
            Comment Delete
        </h1>
    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-danger rounded-pill px-4" type="submit">
                Delete
            </button>
        </form>

    </div>

</div>

{% endblock %}

commentapp/templates/commentapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class = "my-5">
        <h1>
            Comment Update
        </h1>
    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'commentapp:update' pk=target_comment.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4" type="submit">
                Submit
            </button>
        </form>

    </div>

</div>

{% endblock %}