accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = "articleapp"

urlpatterns = [
    path("temp/", TempView.as_view(), name="temp"),
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete"),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscribeView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path("sub/<int:pk>", SubscribeView.as_view(), name="sub"),
    path("list/>", SubscriptionListView.as_view(), name="list"),
]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('article/', include('articleapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('like/', include('likeapp.urls')),

    path('', hello_world)
] + static(
    settings.MEDIA_URL, document_root = settings.MEDIA_ROOT,
)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    image = models.ImageField(upload_to='article/', null=False)
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True)

    like = models.IntegerField(default=0)

    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% include 'header.html' %}
    {% include 'head.html' %}

    {% block content %}
    {% endblock %}


    {% include 'header.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center;">
    <div class="mt-4">
        <span>nav1</span>
        <span>nav2</span>
        <span>nav3</span>
        <span>nav4</span>
    </div>
    <div class="my-2">
        <h4 style="font-family: 'Pacifico', cursive;">
            Techit
        </h4>
    </div>
</div>

templates/head.html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">


<style>
    a {
        color: black;
        text-decoration: none;
    }
    a:hover {
        color: black;
    }

    .material-symbols-outlined {
      font-variation-settings:
      'FILL' 0,
      'wght' 400,
      'GRAD' 0,
      'opsz' 24
    }

    @media (max-width: 768px) {
        html {
            font-size: 12px;
        }
    }

</style>

templates/header.html
<div style = "text-align: center;">
    <div>
        <h1 class="my-5" style="font-family: 'Pacifico', cursive;">
            <a href="{% url 'accountapp:hello_world' %}">Techit</a>
        </h1>
    </div>
    <div class="mb-5">
        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'articleapp:list' %}">
                <b>List</b>
            </a>
        </span>

        <span class="btn btn-warning rounded-pill px-3 my-1">
            <b>nav2</b>
        </span>

        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'subscribeapp:list' %}">
                <b>Subscription</b>
            </a>
        </span>


        {% if user.is_authenticated %}

        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <b>MyPage</b>
            </a>
        </span>
        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'accountapp:logout' %}">
                <b>Logout</b>
            </a>
        </span>
        {% else %}
        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'accountapp:login' %}">
                <b>Login</b>
            </a>
        </span>
        <span class="btn btn-warning rounded-pill px-3 my-1">
            <a href="{% url 'accountapp:create' %}">
                <b>SignUp</b>
            </a>
        </span>
        {% endif %}
    </div>
</div>

templates/list_fragment.html
<style>

  .container div {
    width: 10rem;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 8px;
  }

  @media (min-width: 768px) {
    .container div {
       width: 17rem;
    }
  }

  .container img {
    width: 100%;
    border-radius: 2rem;
  }

</style>


<div class="my-5">

  <div class="container">
    {% for article in article_list %}

    <a href="{% url 'articleapp:detail' pk=article.pk %}">
      <div class="item1">
        <img src="{{ article.image.url }}" alt="">
      </div>
    </a>

    {% endfor %}
  </div>

  <div class="text-center my-5">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
               class="btn btn-secondary rounded-pill">
                {{ page_obj.previous_page_number }}
            </a>
        {% endif %}
            <a href="#"
               class="btn btn-dark rounded-pill">
                {{ page_obj.number }}
            </a>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
               class="btn btn-secondary rounded-pill">
                {{ page_obj.next_page_number }}
            </a>
        {% endif %}
    </div>


    <div class="my-5 text-center">

        <a href="{% url 'articleapp:create' %}"
           class="btn btn-dark rounded-pill px-5">
            <b>Write</b>
        </a>

    </div>


</div>


<script src="https://unpkg.com/magic-grid/dist/magic-grid.cjs.js"></script>
<script>
  let magicGrid = new MagicGrid({
    container: '.container',
    animate: true,
    gutter: 12,
    static: true,
    useMin: true
  });

  magicGrid.listen();

  var masonrys = document.getElementsByTagName("img")

  for (let i = 0; i < masonrys.length; i++) {
    masonrys[i].addEventListener('load', function () {
      magicGrid.positionItems();
    }, false)
  }
</script>