accountapp/urls.py
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountLoginView, AccountLogoutView, AccountDetailView, \
    AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", AccountLogoutView.as_view(), name="logout"),

    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

articleapp/urls.py
from django.urls import path

from articleapp.views import TempView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView

app_name = "articleapp"

urlpatterns = [
    path("temp/", TempView.as_view(), name="temp"),
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>/", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete"),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentUpdateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path("create/", CommentCreateView.as_view(), name="create"),
    path("update/<int:pk>/", CommentUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", CommentDeleteView.as_view(), name="delete"),
]

techit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accountapp.views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profile/', include('profileapp.urls')),
    path('article/', include('articleapp.urls')),
    path('comment/', include('commentapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('like/', include('likeapp.urls')),

    path('', hello_world)
] + static(
    settings.MEDIA_URL, document_root = settings.MEDIA_ROOT,
)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    image = models.ImageField(upload_to='article/', null=False)
    title = models.CharField(max_length=255, null=False)
    content = models.TextField(null=True)

    like = models.IntegerField(default=0)

    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

articleapp/forms.py
from django.forms import models, ModelForm

from articleapp.models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = [
            'image',
            'title',
            'content',
        ]

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


# Create your views here.
class TempView(TemplateView):
    template_name = 'articleapp/temp.html'

class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20


@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articleapp/create.html'
    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articleapp/update.html'
    context_object_name = 'target_article'
    def get_success_url(self):
        return reverse('articleapp:detail',
                       kwargs={'pk': self.object.pk})

@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    template_name = 'articleapp/delete.html'
    context_object_name = 'target_article'
    def get_success_url(self):
        return reverse('accountapp:hello_world')

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class = "my-5">
        <h1>
            Article Create
        </h1>
    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4" type="submit">
                Submit
            </button>
        </form>

    </div>

</div>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class = "my-5">
        <h1>
            Article Delete
        </h1>
        <p>
            delete article : {{ target_article.title }}
        </p>
    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-danger rounded-pill px-4" type="submit">
                Submit
            </button>
        </form>

    </div>

</div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class="my-5">
        <h1>
            {{ target_article.title }}
        </h1>
        <p>
            {{ target_article.created_at }}
        </p>
    </div>

    <div>
        <span style="color: #F77"
              class="material-symbols-outlined">
            favorite
        </span>
        <span style="verticle-align: top;">
            Likes : {{ target_article.like }}
        </span>
    </div>


    <div class="my-5">
        {% if target_article.writer %}
        <a href="{% url 'accountapp:detail' pk=target_article.writer.pk %}">
            <img style="width: 2.5rem; height: 2.5rem; object-fit: cover;
                            border-radius: 50%;"
                 src="{{ target_article.writer.profile.image.url }}" alt="">
            <span class="mx-2">
                    {{ target_article.writer.profile.nickname }}
            </span>
        </a>
        {% else %}
        <h6>
            Unkown
        </h6>
        {% endif %}
    </div>

    <hr class="my-5">

    <div style="max-width: 900px; margin: auto">

        <div>
            <img style="width: 30%; border-radius: 3rem;"
                 src="{{ target_article.image.url }}" alt="">
        </div>

        <div class="my-5">
            {{ target_article.content|linebreaks }}
        </div>

        {% if user == target_article.writer %}
        <div>
            <a href="{% url 'articleapp:update' pk=target_article.pk %}"
               class="btn btn-primary rounded-pill px-5 my-5">
                Update
            </a>
            <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
               class="btn btn-danger rounded-pill px-5 my-5">
                Delete
            </a>
        </div>
        {% endif %}
        <div>

            {% for comment in target_article.comments.all %}
            <div style="border: solid #777; border-radius: 2rem; "
                    class="my-2 p-3 text-start">
                <div>
                    <img style="width: 2.5rem; height: 2.5rem;
                                border-radius: 50%; object-fit: cover"
                         src="{{ comment.writer.profile.image.url }}" alt="">
                    <span class="mx-2">
                        {{ comment.writer.profile.nickname }}
                    </span>
                    <span class="ms-5">
                        {{ comment.created_at }}
                    </span>
                </div>
                <div>
                    {{ comment.content|linebreaks }}
                </div>

                {% if user == comment.writer %}
                <div class="text-end">
                    <a class="btn btn-warning rounded-pill btn-sm px-4 py-0"
                       href="{% url 'commentapp:update' pk=comment.pk %}">
                        Update
                    </a>
                </div>
                {% endif %}
                {% if user == comment.writer %}
                <div class="text-end">
                    <a class="btn btn-danger rounded-pill btn-sm px-4 py-0"
                       href="{% url 'commentapp:delete' pk=comment.pk %}">
                        Delete
                    </a>
                </div>
                {% endif %}
            </div>
            {% endfor %}

        </div>

        <hr class="my-2">
        <h3>
            Comment
        </h3>
        <div class="text-start">
            {% include 'commentapp/create.html' %}
        </div>
    </div>

</div>

{% endblock %}

articleapp/templates/articleapp/temp.html
{% extends 'base.html' %}

{% block content %}
<div>
    <style>

        .container div {
          width: 280px;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 8px;
        }

        .container img {
            width: 100%;
            border-radius: 2rem;
        }

    </style>
    <div class="container">
        <div class="item1">
                <img src = "https://picsum.photos/200/300" alt="">
        </div>
        <div class="item2">
            <img src = "https://picsum.photos/100/100" alt=""></div>
        <div class="item3">
            <img src = "https://picsum.photos/250/300" alt=""></div>
        <div class="item4">
            <img src = "https://picsum.photos/200" alt=""></div>
        <div class="item5">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item6">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item7">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item8">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item9">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item10">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item11">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item12">
            <img src = "https://picsum.photos/200/300" alt=""></div>
        <div class="item13">
            <img src = "https://picsum.photos/200/300" alt=""></div>
    </div>

</div>

<script src="https://unpkg.com/magic-grid/dist/magic-grid.cjs.js"></script>

<script>
    let magicGrid = new MagicGrid({
      container: '.container',
      animate: true,
      gutter: 30,
      static: true,
      useMin: true
    });

    magicGrid.listen();
    var masonrys = document.getElementsByTagName("img")

    for (let i = 0; i < masonrys.length; i++) {
      masonrys[i].addEventListener('load', function () {
        magicGrid.positionItems();
      }, false)
    }
</script>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="my-5 text-center">

    <div class = "my-5">
        <h1>
            Article Update
        </h1>
    </div>
    <div style="max-width: 900px; margin: auto">
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-warning rounded-pill px-4" type="submit">
                Submit
            </button>
        </form>

    </div>

</div>

{% endblock %}